### ISSUE TITLE
Consulta archivo env

### ISSUE THREAD

**Issue by AdrianDVnqn** [whoknowsi/pedidosya-scraper-api#1]
Hola, en el env, qué hay que cargar en la variable data markets?

**Comment by whoknowsi** [comment]
Buenas, en la variable data_markets hay que cargar un array de este tipo (podés cargar varios mercados):

[{"marketName": "Carrefour - Market Carapachay (201)", "partnerId": 167737}]

Donde marketName es el nombre del mercado y partnerId es el id que le pone al mercado PedidosYa, si querés que te pase un ejemplo con todos los env mandame un mail y te los paso, lo hago así con env tan enroscado porque para hacer el scrape uso la api de PedidosYa y no quiero tener quilombos jaja

Si querés por ejemplo sacar el partnerId de un mercado en particular podés entrar y ver los fetchs que hace la api de PedidosYa en ese mercado en particular (lo hago así porque por ahora me interesa solo hacer scrape de mercados en particular y no de todo PedidosYa en general) y ves peticiones del estilo https://**/sections?partnerId=372983&max=20&maxProducts=10&offset=0, bueno, partnerId sería ese mismo que uso para hacer el scrape.

También tenés que tener cuidado porque tienen bastantes cositas como para que no te dejen hacer scrape, te reconoce como bot bastante fácil, lo que hago es dividir los mercados en distintas actions de github y hago el scrape por ahí, porque si lo quiero hacer todo de seguido la mitad me falla seguro.
